version: '3.8'

services:
  katuko:
    build:
      context: .
    ports:
      - "8440:8440" 
    restart: unless-stopped 
    volumes:
      - ./katuko.db:/usr/src/data/katuko.db

    # Create your own .env.docker based on .env.docker.example
    env_file:
      - .env.docker
    