version: '3.8'

services:
  makyo:
    build:
      context: .
      args:
        - VITE_MAKYO_OLLAMA_USE_LOCAL_PROXY=$VITE_MAKYO_OLLAMA_USE_LOCAL_PROXY
    ports:
      - "8440:8440" 
    restart: unless-stopped 
    volumes:
      - ./makyo.db:/usr/src/data/makyo.db

    # Create your own .env.docker based on .env.docker.example
    env_file:
      - .env.docker
    